### ISSUE TITLE
[Lease] Unblock leases blocked due to lack of funds for tip after multiple recovery attempts

### ISSUE THREAD

**Issue by desislavva** [nolus-protocol/nolus-money-market#183]
After multiple attempts to complete the opening during Osmosis downtime - leases spent the entire tip amount. Therefore, they fail to complete the opening even after network recovery.

```
nolusd q wasm contract-state smart nolus16c7r8t65eql8ylkmwstg3wffhe7jsaqwu3cxusj6aztcjvh06a7swer998 '{}' --node https://rila-cl.nolus.network:26657/

data:
  opening:
    downpayment:
      amount: "1000"
      ticker: USDC
    in_progress:
      transfer_out:
        ica_account: osmo1emun4x4dyk5a3259gt3zytetk9xsg4s72ukldv4mzh4dcsn285nq30wy8x
    loan:
      amount: "1500"
      ticker: USDC
    loan_interest_rate: 84

```

```
nolusd q contractmanager failures nolus16c7r8t65eql8ylkmwstg3wffhe7jsaqwu3cxusj6aztcjvh06a7swer998 --node https://rila-cl.nolus.network:26657/

failures:
- ack_id: "18844"
  ack_type: timeout
  address: nolus16c7r8t65eql8ylkmwstg3wffhe7jsaqwu3cxusj6aztcjvh06a7swer998
  channel_id: channel-0
  id: "0"
pagination:
  next_key: null
  total: "0"
```
